### ISSUE TITLE
feature request: an option to specify the location of vmlinuz and initrd.gz

### ISSUE THREAD

**Issue by ckhung** [antiX-Linux/iso-snapshot-antix#1]
Hi, I am running antiX-23_386-full (in a virtual machine, but it doesn't matter). When I run iso-snapshot, the default value for "Boot options" is "initrd=/antix23/initrd.gz" because (I guess) this non-standard directory is what I have on the boot command line of my frugal installation with the extlinux boot loader. If I leave this field untouched, the resulting iso file is not bootable because it is still looking for the initrd.gz in the official antiX/ directory. It would be nice to have an extra option to specify the directory of vmlinuz and initrd.gz in the output iso file so that these two options can be used together and make the iso file still bootable with non-standard directory containing vmlinuz and initrd.gz. Thanks!

**Comment by anticapitalista** [comment]
Thanks but that is too much work

**Comment by ckhung** [comment]
Or, maybe add a reminder that vmlinuz and initrd will always be created in the antiX/ directory? Or remove this clause altogether from the editable window and just display it as uneditable info?

**Comment by anticapitalista** [comment]
BTW our latest stuff is over at GitLab

https://gitlab.com/antiX-Linux/iso-snapshot-antix
